### ISSUE TITLE
Data access

### ISSUE THREAD

**Issue by vishalned** [nasaharvest/presto#12]
Hey, I am trying to generate new data and could use some help. 
Firstly, I cannot find the script generate_data.py, so not sure where that is. 
Secondly, i just wanted to know how you collect the S1 and S2 data, i do not see any ee.ImageCollection in the scripts for this, and was wondering how you did this. 

Would be great if I could get some help on this. Thanks in advance.

**Comment by gabrieltseng** [comment]
Hi @vishalned ,

I've added the `generate_data.py` script (in [this PR](https://github.com/nasaharvest/presto/pull/13)). Apologies for missing it.

For the S1 and S2 data, we use [OpenMapFlow](https://github.com/nasaharvest/openmapflow) to create the EarthEngine image (the function is imported [in this line](https://github.com/nasaharvest/openmapflow), and [defined here](https://github.com/nasaharvest/openmapflow/blob/144723ee3a45acba7b548a0ddf1fe22c7df508a7/openmapflow/ee_exporter.py#L109) in the OpenMapFlow library). 

I hope this helps!

**Comment by vishalned** [comment]
Thanks for the quick reply, this is very helpful

**Comment by vishalned** [comment]
Can I also ask one last question on the dynamic_world_samples. I read from the paper your sampling strategy to get the region of interests, and was wondering if you had a public script that did the same. I am trying to enlarge this dataset, and collect more regions and hence was curious.

**Comment by gabrieltseng** [comment]
In [this function](https://github.com/nasaharvest/presto/blob/main/presto/dataops/dataset.py#L402) we split the dynamic world samples into different shards, which we group together for an export (the file is [saved in the data folder](https://github.com/nasaharvest/presto/blob/main/data/dynamic_world_samples.geojson)).

**Comment by vishalned** [comment]
Yup, I got that part, but my question was regarding the dynamic_world_samples geojson itself. You have roughly 24k different polygons, my question was on the script used to create this, and the possibility for extension of the dataset to more polygons. (I can do it myself, but just wondering if you already have a public script about creating the geojson 😃). Thanks

**Comment by gabrieltseng** [comment]
Ah, I see. 

The geojson comes from dynamic world themselves; they share their training data [here](https://doi.pangaea.de/10.1594/PANGAEA.933475). 

The geojson is a geojson version of the `.xlsx` file they share.

**Comment by vishalned** [comment]
Got it, thanks a lot. Closing the issue now.
