### ISSUE TITLE
Required units for precipitation unclear

### ISSUE THREAD

**Issue by kvantricht** [nasaharvest/presto#19]
Hi guys,

we're still working on setting up the first Presto encoder attempt from our side and we're facing issues with precipitation as an input. In general, I think there's a bit a of lack on documentation with regards to expected units for inputting data into Presto (like Sentinel-2 required to be in 1E4 scaling, Sentinel-1 required to be in decibels, etc.). I think we figured out most on our own, but for precipitation we're puzzled. 
We see the `ERA5_DIV_VALUES ` being 0.03 for precipitation. At the moment, we are feeding just the monthly sum in `mm`, but after normalization, the values in `x` explode due to this `0.03` factor. So what's the expected units?

https://github.com/nasaharvest/presto/blob/613265efac15c8c97a28d94fc2110a2d38e8a5e0/presto/dataops/pipelines/s1_s2_era5_srtm.py#L53:L55

Also note that the commented notebook where the values supposedly come from is inaccessible to us.

**Comment by gabrieltseng** [comment]
Hi @kvantricht ,

We are using the [ERA5 Land monthly averaged values](https://developers.google.com/earth-engine/datasets/catalog/ECMWF_ERA5_LAND_MONTHLY) - in this case, the unit for the precipitation (`total_precipitation`) is in metres. 

I'll make a note in the README making this more explicit.

**Comment by kvantricht** [comment]
We're using [ÀgERA5](https://cds.climate.copernicus.eu/cdsapp#!/dataset/sis-agrometeorological-indicators?tab=overview) instead which is derived ERA5 so I think fairly compatible. But precipitation is daily in `mm` which we accumulated to monthly values. Thanks for clarifying, I'll convert to `m`!
