### ISSUE TITLE
Issues loading pretrained model

### ISSUE THREAD

**Issue by kvantricht** [nasaharvest/presto#21]
When I'm trying to install Presto as a package not in editable mode (e.g. to pack it to run on our cluster), I'm experiencing a couple of issues:

- the current pretrained model loading method does not work as the model weights are not considered as package data (probably separate issue).
- An alternative would be to accept a non-default model weights location in the `load_pretrained` method [here](https://github.com/nasaharvest/presto/blob/main/presto/presto.py#L788) but at the moment this is not possible
- As a last resort, I was trying to copy the `data` folder manually and using `update_data_dir` from [here](https://github.com/nasaharvest/presto/blob/main/presto/utils.py#L14), but while the `data_dir` variable is successfully updated, `default_model_path` from [here](https://github.com/nasaharvest/presto/blob/main/presto/utils.py#L26) is not, so it has actually no effect for loading the pretrained model

**Comment by gabrieltseng** [comment]
In addition to the fix in #22, I think it might make sense to move the weights into the `presto` folder - what do you think?

**Comment by kvantricht** [comment]
Yes I think that makes sense, although it needs to be tested if that would resolve the issue. Pathlike reference to package files doesn't always work on all systems.

**Comment by gabrieltseng** [comment]
Okay - I'll make this change (with some tests) in addition to the notes you left in #20 to a new PR
