### ISSUE TITLE
TreeSatAI evaluation

### ISSUE THREAD

**Issue by isaaccorley** [nasaharvest/presto#3]
My understanding is that the TreeSatAI dataset is multilabel and the labels can be loaded from the labels.json file provided with the dataset. However, on [this line](https://github.com/nasaharvest/presto/blob/f943e9d00c12f79ce694ec68ac708660b01444fc/presto/eval/treesat_eval.py#L75) it appears that you are taking the label from the filename and treating it not as a multilabel task but just a multiclass task. Is this correct?

**Comment by gabrieltseng** [comment]
Thanks for pointing this out, and apologies for the error. I'll work on a fix ASAP

**Comment by isaaccorley** [comment]
I think it's fine as long as you clarify what task you are doing. It wasn't clear from the paper or any readme until I dived in the code itself.

**Comment by gabrieltseng** [comment]
Hi @isaaccorley  - thanks again for pointing this out.

I've updated the code - the new results are in the PR, and I'll update them on arxiv too.
