### ISSUE TITLE
availability of pretrained models

### ISSUE THREAD

**Issue by Geethen** [nasaharvest/presto#4]
I may have missed it, but I cannot seem to see the model checkpoints. Could these be made available please?

**Comment by gabrieltseng** [comment]
Hi! 

The trained model is available here: https://github.com/nasaharvest/presto/blob/main/data/default_model.pt

You can load the pretrained model with the following code:

```python
from presto import Presto

encoder_decoder = Presto.load_pretrained()
```

**Comment by Geethen** [comment]
Hi, Thanks for the heads up:) I missed this. Great work. Thank you for sharing.

**Comment by amirafshari** [comment]
It's only 3 MB?!

**Comment by gabrieltseng** [comment]
Yes - only 3MB!
